# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 140
semi: true
trailingComma: "es5"
xmlWhitespaceSensitivity: "strict"
